name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Debug
        run: env | grep AWS

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
          docker build -t slot-machine .
          docker tag slot-machine:latest 307946634710.dkr.ecr.us-east-1.amazonaws.com/slot-machine:latest

      - name: Push Docker image to ECR
        run: |
          docker push 307946634710.dkr.ecr.us-east-1.amazonaws.com/slot-machine:latest

      - name: Apply Terraform Configuration
        run: |
          terraform init
          terraform apply -auto-approve
